### ISSUE TITLE
Welche zusätzlichen Plugins brauche ich?

### ISSUE THREAD

**Issue by fabiandnl** [B33fb0n3/Bungeesystem#1]
Wollte das gerade bei mir in eclipse importieren und hab in den Properties als external Jar Bungeecord waterfall hinzugefügt. Mir wird immer noch viel rotes Zeug angezeigt und kann das Plugin nicht bauen. Was braucht das Bungeecord System noch?

**Comment by B33fb0n3** [comment]
# Allgemein
An sich brauchst du nur den hochgeladenen Source Code herunterladen.

 # Maven
Per Maven kannst du die Dependencies direkt installieren und das Plugin verändern.

# Artefacts
Alternativ kannst du auch die einzelnen Dependencies als Artefacts hinzufügen.

# Zu deiner Frage
Da Waterfall ein Fork von Bungeecord ist und ich lediglich Methoden von Bungeecord selbst verwendet habe, sollten dadurch die Fehler behoben sein. 
![0C0676CB-0270-4E3E-86A0-B12FBFA940E4](https://user-images.githubusercontent.com/65173484/200107515-07d8300c-2805-4256-acc3-1cccd4c0ab63.jpeg)
Im Screenshot siehst du noch die anderen Dependencies, die du benötigst, um beispielsweise eine erfolgreiche Verbindung mit der Datenbank herstellen zu können. Das dabei grün umrandete hast du bereits mit Waterfall ersetzt.

Falls du weitere Fragen hast, antworte gerne hierauf. Alternativ wird es bald geschlossen.
Vielen Dank, dass du das Plugin verbessern möchtest <3

**Comment by fabiandnl** [comment]
Hi! 
Danke für die schnelle Rückmeldung! Da ich das Ganze via eclipse nutzen wollte, hat mir das nur ein kleines Stück geholfen. Ich habe es jetzt viel einfacher über Intelij gemacht, da kann man es ja einfach über Git importieren. Nun klappt alles hervorragend! Ich wollte nicht viel verändern, sondern einfach mal schauen was ich noch so "drauf" habe. Nochmals vielen Dank für das tolle System und die Freigabe des Sourcecodes! :)

Viele Grüße

**Comment by B33fb0n3** [comment]
Ja IntelliJ macht einiges einfacher (wozu ich übrigens auch präferiere). Ich freue mich, dass es dir gefällt.

**Comment by fabiandnl** [comment]
Ich habe gerade noch eine Frage dazu, weil ich es einfach nicht hin bekomme. Ich das ganze ein Maven Projekt? Wo finde ich meine fertige Jar Datei die ich auf den Server ziehe? Habe jetzt echt lange gesucht, das mehrfach gebaut aber finde einfach die Datei nicht

**Comment by fabiandnl** [comment]
habs hin bekommen. Wir ist dafür aber etwas anderes aufgefallen: Und zwar bekommt man seitdem du das Update veröffentlicht hat durchgehend die Meldung, dass eine neue Version verfügbar ist (also bei der neusten Version, die man von Spigot herunterladen kann)

**Comment by B33fb0n3** [comment]
Korrekt, ich nutze grundsätzlich Maven. Freut mich, dass es geklappt hat. 
Danke für die Rückmeldung bezüglich der Update Message. Die angepasste .jar werde ich im laufe des Tages hochladen. Entweder lädst du sie dir dann dort runter oder du änderst die Version in der plugin.yml auf die aktuelle + 0.1
